# Generated by Django 3.1.7 on 2021-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_product'),
        ('account', '0002_auto_20210318_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_feed',
            field=models.ManyToManyField(related_name='liked_user', through='feed.FeedLike', to='feed.Feed'),
        ),
    ]
