# Generated by Django 3.1.7 on 2021-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='product',
        ),
        migrations.AddField(
            model_name='character',
            name='products',
            field=models.ManyToManyField(through='product.CharacterProduct', to='product.Product'),
        ),
    ]
