# Generated by Django 3.1.7 on 2021-03-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_transaction_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='cvc',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
