# Generated by Django 3.1.7 on 2021-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20210318_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='condition',
            field=models.CharField(max_length=45),
        ),
    ]
