# Generated by Django 3.1.7 on 2021-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='product',
            new_name='products',
        ),
    ]
