# Generated by Django 3.1.7 on 2021-03-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210318_0729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendedproduct',
            table='recommended_products',
        ),
    ]
