# Generated by Django 3.1.7 on 2021-03-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210321_0857'),
        ('feed', '0004_auto_20210319_0058'),
    ]

    operations = [
    ]
